---
apiVersion: v1
data:
  jupyter_notebook_config.py: |
    import os

    password = os.environ.get('JUPYTER_NOTEBOOK_PASSWORD')

    if password:
        import notebook.auth
        c.NotebookApp.password = notebook.auth.passwd(password)
        del password
        del os.environ['JUPYTER_NOTEBOOK_PASSWORD']

    image_config_file = '/home/madi/.jupyter/jupyter_notebook_config.py'

    if os.path.exists(image_config_file):
        with open(image_config_file) as fp:
            exec(compile(fp.read(), image_config_file, 'exec'), globals())
kind: ConfigMap
metadata:
  labels:
    app: ${APPLICATION_NAME}
  name: ${APPLICATION_NAME}-cfg
